[tool.poetry]
name = "compotime"
version = "0.1.0"
description = "A package for compositional time series"
authors = ["Jaume Mateu"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.11,<3.12"
numpy = "^1.24.2"
scipy = "^1.10.1"
pandas = "^2.0.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ruff = "^0.0.261"
pytest = "^7.3.1"
hypothesis = "^6.72.1"
ipython = "^8.12.0"

[tool.black]
line-length = 100
target-version = ["py311"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
